[profile.default]
solc-version = '0.8.22'
src = 'src'
libs = [
    'node_modules',
]

remappings = [
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]

## TODO is this needed here?
[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
